[pytest]

testpaths = tests

addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir

markers =
    smoke: Critical smoke tests
    regression: Full regression tests
    search: Search feature tests