[pytest]

testpaths = tests

addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
    --reruns 1
    --reruns-delay 2

markers =
    smoke: Critical smoke tests
    regression: Full regression tests
    search: Search feature tests
    api: API tests